name:                wntext
version:             0.1.0.0
github:              "own-pt/wntext"
license:             Apache-2.0
author:              "bruno cuconato"
maintainer:          "bcclaro+haskell@gmail.com"
copyright:           "2019 IBM Corporation"

extra-source-files:
- README
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/own-pt/wntext#readme>


default-extensions:
- OverloadedStrings
- NamedFieldPuns
- DuplicateRecordFields

dependencies:
- base >= 4.7 && < 5
- megaparsec == 7.*
- text == 1.*
- generic-trie > 0.2.0 && < 1.0
- mtl == 2.*
- containers == 0.6.*
- filepath == 1.*
- parser-combinators == 1.*
- rdf == 0.1.*
- directory == 1.*
- transformers == 0.5.*
- dlist == 0.8.*
- binary == 0.8.*
- optparse-applicative >= 0.14 && < 1

library:
  source-dirs: src

executables:
  mill:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wntext

tests:
  wntext-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wntext
