name:                mill
version:             0.1.0.0
github:              "own-pt/mill"
license:             Apache-2.0
author:              "bruno cuconato"
maintainer:          "bcclaro+haskell@gmail.com"
copyright:           "2019 IBM Corporation"

extra-source-files:
- README
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/own-pt/mill#readme>


default-extensions:
- OverloadedStrings
- NamedFieldPuns
- DuplicateRecordFields
- TupleSections
- RecordWildCards

dependencies:
- aeson == 1.4.*
- base >= 4.7 && < 5
- bytestring == 0.10.*
- binary == 0.8.*
- containers == 0.6.*
- directory == 1.*
- dlist == 0.8.*
- filepath == 1.*
- list-tries == 0.6.*
- megaparsec == 7.*
- mtl == 2.*
- optparse-applicative >= 0.14 && < 1
- parser-combinators == 1.*
- prettyprinter == 1.*
- rdf == 0.1.*
- shake == 0.17.*
- text == 1.2.*
- transformers == 0.5.*

library:
  source-dirs: src

executables:
  mill:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mill

tests:
  mill-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mill
